# workflow name
name: Deploy to GitHub Pages

# When the workflow runs
on:
  push:
    branches:
      - main # change this branch if your main branch has a different name
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Workflow jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          # 使用一个稳定且较新的 OCaml 版本
          ocaml-compiler: '4.14.x'

      - name: Install Forester
        run: opam install forester

      - name: Build project
        run: forester build forest.toml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4